id: opecha:P000315
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG4285
  title: བློ་སྦྱོང་སྐོར་ཕྱོགས་བསྒྲིགས།
  volume:
    784656339dd946779b57ec757bae07a3:
      image_group_id: I1PD100489
      title: Volume 1 of blo sbyong brgya rtsa
      volume_number: 1
      total_pages: 548
    aaf99c09067e4da58f51c8c1b202f6fb:
      image_group_id: I1PD100490
      title: Volume 2 of blo sbyong brgya rtsa
      volume_number: 2
      total_pages: 466
  author: ''
ebook_metadata:
  title: བློ་སྦྱོང་སྐོར་ཕྱོགས་བསྒྲིགས།
  author: ''
  sku: P000315
  cover: cover.jpg
  layers:
  - pagination
