id: P000315
initial_creation_type: ocr
created_at: 12/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W1KG4285
  title: བློ་སྦྱོང་སྐོར་ཕྱོགས་བསྒྲིགས།
  author: ''
  volumes:
    784656339dd946779b57ec757bae07a3:
      image_group_id: I1PD100489
      title: Volume 1 of blo sbyong brgya rtsa
      volume_number: 1
      total_pages: 548
      base_file: v001.txt
    aaf99c09067e4da58f51c8c1b202f6fb:
      image_group_id: I1PD100490
      title: Volume 2 of blo sbyong brgya rtsa
      volume_number: 2
      total_pages: 466
      base_file: v002.txt
